name: my_todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  rxdart: ^0.27.7
  image_picker: ^0.8.9
  shared_preferences: ^2.1.2
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  device_preview: ^1.1.0
  pull_to_refresh: ^2.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_svg: ^2.0.7
  permission_handler: ^11.0.1
  flutter_switch: ^0.3.2
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  mime_type: ^1.0.0
  device_info_plus: ^8.0.0
  share_plus: ^6.3.4
  sqflite: ^2.3.2
  path: ^1.8.3
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  go_router: ^13.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
